sentinel:
  name: sentinel-1
  host: 1.2.3.4:26379
  password: 
  master_name:
    - master-1
    - master-2

dns-providers:
  - name: huaweicloud-private-1
    type: huaweicloud-private
    access_key: ak
    secret_key: sk
    region: cn-east-3
    domain: demo.com
    zone_id: id
    record:
      - type: A
        ttl: 1